default:
  tags:
    - docker
  # Image from https://hub.docker.com/_/gcc/ based on Debian
  image: gcc:9

.autoconf:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y git make ${INSTALL_COMPILER} automake autoconf libtool ${INSTALL_EXTRA}
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS} || cat config.log
    - make
    - make check
  variables:
    INSTALL_COMPILER: gcc g++

autoconf-gcc:
  extends: .autoconf
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS}
    - make
    - make distcheck

autoconf-clang:
  extends: .autoconf
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS}
    - make
    - make distcheck
  variables:
    INSTALL_COMPILER: clang
    CC: clang

enable-assertions:
  extends: .autoconf
  variables:
    CONFIG_FLAGS: --enable-assertions

enable-dnn-debug-float:
  extends: .autoconf
  variables:
    CONFIG_FLAGS: --enable-dnn-debug-float
